apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genepay-ingress
  namespace: genepay
spec:
  ingressClassName: nginx
  rules:
    - host: app.genepay.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-dashboard
                port:
                  number: 80
    - host: chain.genepay.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blockchain-dashboard
                port:
                  number: 80
    - host: api.genepay.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 8080
