apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: genepay
resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - postgres.yaml
  - biometric-service.yaml
  - blockchain-relay.yaml
  - payment-service.yaml
  - admin-dashboard.yaml
  - blockchain-dashboard.yaml
  - ingress.yaml

images:
  - name: udarawick/genepay-admin-dashboard
    newName: 357343207025.dkr.ecr.ap-southeast-1.amazonaws.com/genepay-admin-dashboard
    newTag: latest

  - name: udarawick/genepay-payment-service
    newName: 357343207025.dkr.ecr.ap-southeast-1.amazonaws.com/genepay-payment-service
    newTag: latest

  - name: udarawick/genepay-biometric-service
    newName: 357343207025.dkr.ecr.ap-southeast-1.amazonaws.com/genepay-biometric-service
    newTag: latest

  - name: udarawick/genepay-blockchain-dashboard
    newName: 357343207025.dkr.ecr.ap-southeast-1.amazonaws.com/genepay-blockchain-dashboard
    newTag: latest

  - name: udarawick/genepay-blockchain-service
    newName: 357343207025.dkr.ecr.ap-southeast-1.amazonaws.com/genepay-blockchain-service
    newTag: latest
